###
# 02 - type()
# There are several types in Python (int, float, bool, str, list, tuple, dict, set, None...)
###
print(type(1))
print(type(1.0))
print(type(True))
print(type("Hello"))
print(type(2345324345234))
# print(type([1, 2, 3]))
# print(type((1, 2, 3)))
# print(type({1, 2, 3}))
# print(type({1: "a", 2: "b", 3: "c"}))
print(type(None))
print('Es el único tipo que representa la ausencia de valor.')
print(type(1+2j))
print('Se usa en matemáticas para representar complejos.')